// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

package no.mechatronics.sfi.fmu_proxy.grpc;

/**
 * Protobuf enum {@code no.mechatronics.sfi.fmu_proxy.grpc.CausalityProto}
 */
public enum CausalityProto
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNDEFINED_CAUSALITY = 0;</code>
   */
  UNDEFINED_CAUSALITY(0),
  /**
   * <code>INPUT_CAUSALITY = 1;</code>
   */
  INPUT_CAUSALITY(1),
  /**
   * <code>OUTPUT_CAUSALITY = 2;</code>
   */
  OUTPUT_CAUSALITY(2),
  /**
   * <code>PARAMETER_CAUSALITY = 3;</code>
   */
  PARAMETER_CAUSALITY(3),
  /**
   * <code>CALCULATED_PARAMETER_CAUSALITY = 4;</code>
   */
  CALCULATED_PARAMETER_CAUSALITY(4),
  /**
   * <code>LOCAL_CAUSALITY = 5;</code>
   */
  LOCAL_CAUSALITY(5),
  /**
   * <code>INDEPENDENT_CAUSALITY = 6;</code>
   */
  INDEPENDENT_CAUSALITY(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNDEFINED_CAUSALITY = 0;</code>
   */
  public static final int UNDEFINED_CAUSALITY_VALUE = 0;
  /**
   * <code>INPUT_CAUSALITY = 1;</code>
   */
  public static final int INPUT_CAUSALITY_VALUE = 1;
  /**
   * <code>OUTPUT_CAUSALITY = 2;</code>
   */
  public static final int OUTPUT_CAUSALITY_VALUE = 2;
  /**
   * <code>PARAMETER_CAUSALITY = 3;</code>
   */
  public static final int PARAMETER_CAUSALITY_VALUE = 3;
  /**
   * <code>CALCULATED_PARAMETER_CAUSALITY = 4;</code>
   */
  public static final int CALCULATED_PARAMETER_CAUSALITY_VALUE = 4;
  /**
   * <code>LOCAL_CAUSALITY = 5;</code>
   */
  public static final int LOCAL_CAUSALITY_VALUE = 5;
  /**
   * <code>INDEPENDENT_CAUSALITY = 6;</code>
   */
  public static final int INDEPENDENT_CAUSALITY_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CausalityProto valueOf(int value) {
    return forNumber(value);
  }

  public static CausalityProto forNumber(int value) {
    switch (value) {
      case 0: return UNDEFINED_CAUSALITY;
      case 1: return INPUT_CAUSALITY;
      case 2: return OUTPUT_CAUSALITY;
      case 3: return PARAMETER_CAUSALITY;
      case 4: return CALCULATED_PARAMETER_CAUSALITY;
      case 5: return LOCAL_CAUSALITY;
      case 6: return INDEPENDENT_CAUSALITY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CausalityProto>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CausalityProto> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CausalityProto>() {
          public CausalityProto findValueByNumber(int number) {
            return CausalityProto.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return no.mechatronics.sfi.fmu_proxy.grpc.Definitions.getDescriptor().getEnumTypes().get(0);
  }

  private static final CausalityProto[] VALUES = values();

  public static CausalityProto valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CausalityProto(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:no.mechatronics.sfi.fmu_proxy.grpc.CausalityProto)
}

