// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definitions.proto

package no.mechatronics.sfi.fmu_proxy.grpc;

public interface StatusProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:no.mechatronics.sfi.fmu_proxy.grpc.StatusProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.no.mechatronics.sfi.fmu_proxy.grpc.StatusCodeProto code = 1;</code>
   */
  int getCodeValue();
  /**
   * <code>.no.mechatronics.sfi.fmu_proxy.grpc.StatusCodeProto code = 1;</code>
   */
  no.mechatronics.sfi.fmu_proxy.grpc.StatusCodeProto getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
