
trigger:
  - master

jobs:
  - job: cpp_vcpkg
    timeoutInMinutes: 120

    pool:
      vmImage: 'vs2017-win2016'

    steps:

      - task: Bash@3
        inputs:
          script: |
            git submodule update --init --recursive
          workingDirectory: '$(system.defaultWorkingDirectory)'
          targetType: inline

      - task: Bash@3
        inputs:
          script: |
            git clone https://github.com/Microsoft/vcpkg.git
            cd vcpkg
            ./bootstrap-vcpkg.bat
            ./vcpkg install curl thrift grpc nlohmann-json libzip[core] spdlog boost-program-options boost-ublas boost-odeint --triplet x64-windows
          workingDirectory: '$(system.defaultWorkingDirectory)'
          targetType: inline

      - task: CMake@1
        inputs:
          workingDirectory: '$(system.defaultWorkingDirectory)/cpp/FMU-proxy/cmake-build-release'
          cmakeArgs: 'cmake -G "CodeBlocks - NMake Makefiles" .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe" -DCMAKE_TOOLCHAIN_FILE=../../../vcpkg/scripts/buildsystems/vcpkg.cmake -DFMU_PROXY_BUILD_TESTS=OFF'

      - task: CMake@1
        inputs:
          workingDirectory: '$(system.defaultWorkingDirectory)/cpp/FMU-proxy/cmake-build-release'
          cmakeArgs: '--build . --target all'


  - job: cpp_conan
    timeoutInMinutes: 30

    pool:
      vmImage: 'vs2017-win2016'

    steps:

      - task: Bash@3
        inputs:
          script: |
            git submodule update --init --recursive
          workingDirectory: '$(system.defaultWorkingDirectory)'
          targetType: inline

      - task: Bash@3
        inputs:
          script: |
            python -m pip install --upgrade pip
            sudo pip install conan --upgrade

            conan remote add helmesjo "https://api.bintray.com/conan/helmesjo/public-conan"
            conan remote add inexorgame "https://api.bintray.com/conan/inexorgame/inexor-conan"

            conan install . -s build_type=Release --install-folder=cmake-build-release -o grpc=False -o thrift=False --build=missing
          workingDirectory: '$(system.defaultWorkingDirectory)/cpp/FMU-proxy'
          targetType: inline

      - task: CMake@1
        inputs:
          workingDirectory: '$(system.defaultWorkingDirectory)/cpp/FMU-proxy/cmake-build-release'
          cmakeArgs: 'cmake -G "Visual Studio 15 2017 Win64" .. -DFMU_PROXY_USING_CONAN=ON -DFMU_PROXY_BUILD_TESTS=OFF -DFMU_PROXY_WITH_THRIFT=OFF -DFMU_PROXY_WITH_GRPC=OFF'

      - task: VSBuild@1
        inputs:
          solution: '$(system.defaultWorkingDirectory)/cpp/FMU-proxy/cmake-build-release/*.sln'
          configuration: 'release'
          platform: 'x64'


  - job: jvm
    timeoutInMinutes: 20
    
    pool:
      vmImage: 'vs2017-win2016'

    steps:
      - task: Gradle@2
        inputs:
          workingDirectory: '$(system.defaultWorkingDirectory)/java/FMU-proxy/'
          gradleWrapperFile: '$(system.defaultWorkingDirectory)/java/FMU-proxy/gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'dependencies test'
