// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package no.mechatronics.sfi.grpc_fmu;

public final class GenericFmuProto {
  private GenericFmuProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\034no.mechatronics.sfi.grp" +
      "c_fmu\032\021definitions.proto2\364\007\n\021GenericFmuS" +
      "ervice\022X\n\016CreateInstance\022#.no.mechatroni" +
      "cs.sfi.grpc_fmu.Empty\032!.no.mechatronics." +
      "sfi.grpc_fmu.Int\022V\n\014GetModelName\022#.no.me" +
      "chatronics.sfi.grpc_fmu.Empty\032!.no.mecha" +
      "tronics.sfi.grpc_fmu.Str\022g\n\021GetModelVari" +
      "ables\022#.no.mechatronics.sfi.grpc_fmu.Emp" +
      "ty\032-.no.mechatronics.sfi.grpc_fmu.Scalar" +
      "Variables\022W\n\016GetCurrentTime\022!.no.mechatr" +
      "onics.sfi.grpc_fmu.Int\032\".no.mechatronics" +
      ".sfi.grpc_fmu.Real\022U\n\014IsTerminated\022!.no." +
      "mechatronics.sfi.grpc_fmu.Int\032\".no.mecha" +
      "tronics.sfi.grpc_fmu.Bool\022U\n\004Init\022).no.m" +
      "echatronics.sfi.grpc_fmu.InitRequest\032\".n" +
      "o.mechatronics.sfi.grpc_fmu.Bool\022W\n\004Step" +
      "\022).no.mechatronics.sfi.grpc_fmu.StepRequ" +
      "est\032$.no.mechatronics.sfi.grpc_fmu.Statu" +
      "s\022`\n\tTerminate\022..no.mechatronics.sfi.grp" +
      "c_fmu.TerminateRequest\032#.no.mechatronics" +
      ".sfi.grpc_fmu.Empty\022Y\n\005Reset\022*.no.mechat" +
      "ronics.sfi.grpc_fmu.ResetRequest\032$.no.me" +
      "chatronics.sfi.grpc_fmu.Status\022P\n\004Read\022%" +
      ".no.mechatronics.sfi.grpc_fmu.VarRead\032!." +
      "no.mechatronics.sfi.grpc_fmu.Var\022U\n\005Writ" +
      "e\022&.no.mechatronics.sfi.grpc_fmu.VarWrit" +
      "e\032$.no.mechatronics.sfi.grpc_fmu.StatusB" +
      "\021B\017GenericFmuProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          no.mechatronics.sfi.grpc_fmu.FmiDefinitions.getDescriptor(),
        }, assigner);
    no.mechatronics.sfi.grpc_fmu.FmiDefinitions.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
