# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import definitions_pb2 as definitions__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FmuServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateInstanceFromCS = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/CreateInstanceFromCS',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=definitions__pb2.UIntProto.FromString,
        )
    self.CreateInstanceFromME = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/CreateInstanceFromME',
        request_serializer=definitions__pb2.IntegratorProto.SerializeToString,
        response_deserializer=definitions__pb2.UIntProto.FromString,
        )
    self.GetGuid = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/GetGuid',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=definitions__pb2.StrProto.FromString,
        )
    self.GetModelName = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/GetModelName',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=definitions__pb2.StrProto.FromString,
        )
    self.GetModelDescriptionXml = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/GetModelDescriptionXml',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=definitions__pb2.StrProto.FromString,
        )
    self.GetModelStructure = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/GetModelStructure',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=definitions__pb2.ModelStructureProto.FromString,
        )
    self.GetModelVariables = channel.unary_stream(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/GetModelVariables',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=definitions__pb2.ScalarVariableProto.FromString,
        )
    self.GetCurrentTime = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/GetCurrentTime',
        request_serializer=definitions__pb2.UIntProto.SerializeToString,
        response_deserializer=definitions__pb2.RealProto.FromString,
        )
    self.IsTerminated = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/IsTerminated',
        request_serializer=definitions__pb2.UIntProto.SerializeToString,
        response_deserializer=definitions__pb2.BoolProto.FromString,
        )
    self.Init = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/Init',
        request_serializer=definitions__pb2.InitRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.BoolProto.FromString,
        )
    self.Step = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/Step',
        request_serializer=definitions__pb2.StepRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.StatusProto.FromString,
        )
    self.Terminate = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/Terminate',
        request_serializer=definitions__pb2.UIntProto.SerializeToString,
        response_deserializer=definitions__pb2.BoolProto.FromString,
        )
    self.Reset = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/Reset',
        request_serializer=definitions__pb2.UIntProto.SerializeToString,
        response_deserializer=definitions__pb2.StatusProto.FromString,
        )
    self.ReadInteger = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/ReadInteger',
        request_serializer=definitions__pb2.ReadRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.IntReadProto.FromString,
        )
    self.ReadReal = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/ReadReal',
        request_serializer=definitions__pb2.ReadRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.RealReadProto.FromString,
        )
    self.ReadString = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/ReadString',
        request_serializer=definitions__pb2.ReadRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.StrReadProto.FromString,
        )
    self.ReadBoolean = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/ReadBoolean',
        request_serializer=definitions__pb2.ReadRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.BoolReadProto.FromString,
        )
    self.BulkReadInteger = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/BulkReadInteger',
        request_serializer=definitions__pb2.BulkReadRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.IntListReadProto.FromString,
        )
    self.BulkReadReal = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/BulkReadReal',
        request_serializer=definitions__pb2.BulkReadRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.RealListReadProto.FromString,
        )
    self.BulkReadString = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/BulkReadString',
        request_serializer=definitions__pb2.BulkReadRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.StrListReadProto.FromString,
        )
    self.BulkReadBoolean = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/BulkReadBoolean',
        request_serializer=definitions__pb2.BulkReadRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.BoolListReadProto.FromString,
        )
    self.WriteInteger = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/WriteInteger',
        request_serializer=definitions__pb2.WriteIntegerRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.StatusProto.FromString,
        )
    self.WriteReal = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/WriteReal',
        request_serializer=definitions__pb2.WriteRealRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.StatusProto.FromString,
        )
    self.WriteString = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/WriteString',
        request_serializer=definitions__pb2.WriteStringRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.StatusProto.FromString,
        )
    self.WriteBoolean = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/WriteBoolean',
        request_serializer=definitions__pb2.WriteBooleanRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.StatusProto.FromString,
        )
    self.BulkWriteInteger = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/BulkWriteInteger',
        request_serializer=definitions__pb2.BulkWriteIntegerRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.StatusProto.FromString,
        )
    self.BulkWriteReal = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/BulkWriteReal',
        request_serializer=definitions__pb2.BulkWriteRealRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.StatusProto.FromString,
        )
    self.BulkWriteString = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/BulkWriteString',
        request_serializer=definitions__pb2.BulkWriteStringRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.StatusProto.FromString,
        )
    self.BulkWriteBoolean = channel.unary_unary(
        '/no.mechatronics.sfi.fmu_proxy.grpc.FmuService/BulkWriteBoolean',
        request_serializer=definitions__pb2.BulkWriteBooleanRequestProto.SerializeToString,
        response_deserializer=definitions__pb2.StatusProto.FromString,
        )


class FmuServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateInstanceFromCS(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateInstanceFromME(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetGuid(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetModelName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetModelDescriptionXml(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetModelStructure(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetModelVariables(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCurrentTime(self, request, context):
    """instance methods
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IsTerminated(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Init(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Step(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Terminate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Reset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadInteger(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadReal(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadString(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadBoolean(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BulkReadInteger(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BulkReadReal(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BulkReadString(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BulkReadBoolean(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WriteInteger(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WriteReal(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WriteString(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WriteBoolean(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BulkWriteInteger(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BulkWriteReal(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BulkWriteString(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BulkWriteBoolean(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FmuServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateInstanceFromCS': grpc.unary_unary_rpc_method_handler(
          servicer.CreateInstanceFromCS,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=definitions__pb2.UIntProto.SerializeToString,
      ),
      'CreateInstanceFromME': grpc.unary_unary_rpc_method_handler(
          servicer.CreateInstanceFromME,
          request_deserializer=definitions__pb2.IntegratorProto.FromString,
          response_serializer=definitions__pb2.UIntProto.SerializeToString,
      ),
      'GetGuid': grpc.unary_unary_rpc_method_handler(
          servicer.GetGuid,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=definitions__pb2.StrProto.SerializeToString,
      ),
      'GetModelName': grpc.unary_unary_rpc_method_handler(
          servicer.GetModelName,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=definitions__pb2.StrProto.SerializeToString,
      ),
      'GetModelDescriptionXml': grpc.unary_unary_rpc_method_handler(
          servicer.GetModelDescriptionXml,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=definitions__pb2.StrProto.SerializeToString,
      ),
      'GetModelStructure': grpc.unary_unary_rpc_method_handler(
          servicer.GetModelStructure,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=definitions__pb2.ModelStructureProto.SerializeToString,
      ),
      'GetModelVariables': grpc.unary_stream_rpc_method_handler(
          servicer.GetModelVariables,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=definitions__pb2.ScalarVariableProto.SerializeToString,
      ),
      'GetCurrentTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetCurrentTime,
          request_deserializer=definitions__pb2.UIntProto.FromString,
          response_serializer=definitions__pb2.RealProto.SerializeToString,
      ),
      'IsTerminated': grpc.unary_unary_rpc_method_handler(
          servicer.IsTerminated,
          request_deserializer=definitions__pb2.UIntProto.FromString,
          response_serializer=definitions__pb2.BoolProto.SerializeToString,
      ),
      'Init': grpc.unary_unary_rpc_method_handler(
          servicer.Init,
          request_deserializer=definitions__pb2.InitRequestProto.FromString,
          response_serializer=definitions__pb2.BoolProto.SerializeToString,
      ),
      'Step': grpc.unary_unary_rpc_method_handler(
          servicer.Step,
          request_deserializer=definitions__pb2.StepRequestProto.FromString,
          response_serializer=definitions__pb2.StatusProto.SerializeToString,
      ),
      'Terminate': grpc.unary_unary_rpc_method_handler(
          servicer.Terminate,
          request_deserializer=definitions__pb2.UIntProto.FromString,
          response_serializer=definitions__pb2.BoolProto.SerializeToString,
      ),
      'Reset': grpc.unary_unary_rpc_method_handler(
          servicer.Reset,
          request_deserializer=definitions__pb2.UIntProto.FromString,
          response_serializer=definitions__pb2.StatusProto.SerializeToString,
      ),
      'ReadInteger': grpc.unary_unary_rpc_method_handler(
          servicer.ReadInteger,
          request_deserializer=definitions__pb2.ReadRequestProto.FromString,
          response_serializer=definitions__pb2.IntReadProto.SerializeToString,
      ),
      'ReadReal': grpc.unary_unary_rpc_method_handler(
          servicer.ReadReal,
          request_deserializer=definitions__pb2.ReadRequestProto.FromString,
          response_serializer=definitions__pb2.RealReadProto.SerializeToString,
      ),
      'ReadString': grpc.unary_unary_rpc_method_handler(
          servicer.ReadString,
          request_deserializer=definitions__pb2.ReadRequestProto.FromString,
          response_serializer=definitions__pb2.StrReadProto.SerializeToString,
      ),
      'ReadBoolean': grpc.unary_unary_rpc_method_handler(
          servicer.ReadBoolean,
          request_deserializer=definitions__pb2.ReadRequestProto.FromString,
          response_serializer=definitions__pb2.BoolReadProto.SerializeToString,
      ),
      'BulkReadInteger': grpc.unary_unary_rpc_method_handler(
          servicer.BulkReadInteger,
          request_deserializer=definitions__pb2.BulkReadRequestProto.FromString,
          response_serializer=definitions__pb2.IntListReadProto.SerializeToString,
      ),
      'BulkReadReal': grpc.unary_unary_rpc_method_handler(
          servicer.BulkReadReal,
          request_deserializer=definitions__pb2.BulkReadRequestProto.FromString,
          response_serializer=definitions__pb2.RealListReadProto.SerializeToString,
      ),
      'BulkReadString': grpc.unary_unary_rpc_method_handler(
          servicer.BulkReadString,
          request_deserializer=definitions__pb2.BulkReadRequestProto.FromString,
          response_serializer=definitions__pb2.StrListReadProto.SerializeToString,
      ),
      'BulkReadBoolean': grpc.unary_unary_rpc_method_handler(
          servicer.BulkReadBoolean,
          request_deserializer=definitions__pb2.BulkReadRequestProto.FromString,
          response_serializer=definitions__pb2.BoolListReadProto.SerializeToString,
      ),
      'WriteInteger': grpc.unary_unary_rpc_method_handler(
          servicer.WriteInteger,
          request_deserializer=definitions__pb2.WriteIntegerRequestProto.FromString,
          response_serializer=definitions__pb2.StatusProto.SerializeToString,
      ),
      'WriteReal': grpc.unary_unary_rpc_method_handler(
          servicer.WriteReal,
          request_deserializer=definitions__pb2.WriteRealRequestProto.FromString,
          response_serializer=definitions__pb2.StatusProto.SerializeToString,
      ),
      'WriteString': grpc.unary_unary_rpc_method_handler(
          servicer.WriteString,
          request_deserializer=definitions__pb2.WriteStringRequestProto.FromString,
          response_serializer=definitions__pb2.StatusProto.SerializeToString,
      ),
      'WriteBoolean': grpc.unary_unary_rpc_method_handler(
          servicer.WriteBoolean,
          request_deserializer=definitions__pb2.WriteBooleanRequestProto.FromString,
          response_serializer=definitions__pb2.StatusProto.SerializeToString,
      ),
      'BulkWriteInteger': grpc.unary_unary_rpc_method_handler(
          servicer.BulkWriteInteger,
          request_deserializer=definitions__pb2.BulkWriteIntegerRequestProto.FromString,
          response_serializer=definitions__pb2.StatusProto.SerializeToString,
      ),
      'BulkWriteReal': grpc.unary_unary_rpc_method_handler(
          servicer.BulkWriteReal,
          request_deserializer=definitions__pb2.BulkWriteRealRequestProto.FromString,
          response_serializer=definitions__pb2.StatusProto.SerializeToString,
      ),
      'BulkWriteString': grpc.unary_unary_rpc_method_handler(
          servicer.BulkWriteString,
          request_deserializer=definitions__pb2.BulkWriteStringRequestProto.FromString,
          response_serializer=definitions__pb2.StatusProto.SerializeToString,
      ),
      'BulkWriteBoolean': grpc.unary_unary_rpc_method_handler(
          servicer.BulkWriteBoolean,
          request_deserializer=definitions__pb2.BulkWriteBooleanRequestProto.FromString,
          response_serializer=definitions__pb2.StatusProto.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'no.mechatronics.sfi.fmu_proxy.grpc.FmuService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
