
name: Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew clean build installDist

#      - uses: actions/upload-artifact@v2
#        with:
#          name: fmu-proxy
#          path: fmu-proxy/build/install

#      - uses: actions/upload-artifact@v2
#        with:
#          name: fmu-proxy-server
#          path: fmu-proxy-server/build/libs/fmu-proxy-server.jar
