
name: Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build (Windows)
        if: startsWith(runner.os, 'Windows')
        run: ./gradlew clean build installDist

      - name: Fetch thrift (Linux)
        if: startsWith(runner.os, 'Linux')
        run: |
          sudo apt-get install thrift-compiler && thrift --version
        shell: bash

      - name: Build (Linux)
        if: startsWith(runner.os, 'Linux')
        run: |
          sudo chmod +x gradlew && ./gradlew clean build installDist
        shell: bash

#      - uses: actions/upload-artifact@v2
#        with:
#          name: fmu-proxy
#          path: fmu-proxy/build/install

#      - uses: actions/upload-artifact@v2
#        with:
#          name: fmu-proxy-server
#          path: fmu-proxy-server/build/libs/fmu-proxy-server.jar
